(global-set-key [f11] 'fullscreen)
(global-set-key [f5] 'goto-line)
(global-set-key [f10] 'make-frame-on-display)
(global-set-key [f9] 'cross)
(global-set-key [delete] 'delete-char)
(global-set-key [backspace] 'delete-backward-char)
(global-set-key (kbd "M-<up>") 'move-line-up)
(global-set-key (kbd "M-<down>") 'move-line-down)
(global-set-key (kbd "C-x p") 'goto-matching-paren)
(global-set-key (kbd "M-C-f") 'find-file-at-point)
